export const Detai = [{
    "year": "2020-12",
    "loanAmount": 0,
    "dateStart": "",
    "dateEnd": "",
    "interest": 0,
    "penalty": 0,
},{
    "year": "2021-01",
    "loanAmount": 0,
    "dateStart": "",
    "dateEnd": "",
    "interest": 0,
    "penalty": 0,
},{
    "year": "2021-02",
    "loanAmount": 0,
    "dateStart": "",
    "dateEnd": "",
    "interest": 0,
    "penalty": 0,
},{
    "year": "2021-03",
    "loanAmountVivek": 12000,
    "dateStartVivek": "28 march",
    "dateEndVivek": "28 april",
    "interestVivek": 0,
    "penaltyVivek": 0,
    "loanAmountKaran": 3000,
    "dateStartKaran": "18 march",
    "dateEndKaran": "18 april",
    "interestKaran": 0,
    "penaltyKaran": 0,
},{
    "year": "2021-04",
    "interestVivek": 120,
    "interestKaran": 30,

    "loanAmountPinal": 5000,
    "dateStartPinal": "2 april",
    "dateEndPinal": "2 may",
    "interestPinal": 0,
    "penaltyPinal": 0,
},{
    "year": "2021-05",
    "interestPinal": 50,

    "loanAmountKunj": 2000,
    "dateStartKunj": "17 may",
    "dateEndKunj": "17 june",
    "interestKunj": 0,
    "penaltyKunj": 0,
    "loanAmountPriyal": 8000,
    "dateStartPriyal": "1 may",
    "dateEndPriyal": "1 june",
    "interestPriyal": 0,
    "penaltyPriyal": 0,
},{
    "year": "2021-06",
    "interestPriyal": 80,

    "loanAmountKunj": 2000,
    "dateStartKunj": "17 june",
    "dateEndKunj": "17 july",
    "interestKunj": 20,
    "penaltyKunj": 0,
    "loanAmountKaran": 5000,
    "dateStartKaran": "11 june",
    "dateEndKaran": "11 july",
    "interestKaran": 0,
    "penaltyKaran": 0,
},{
    "year": "2021-07",
    "interestKaran": 50,
    "interestKunj": 20,

    "loanAmount": 0,
    "dateStart": "",
    "dateEnd": "",
    "interest": 0,
    "penalty": 0,
},{
    "year": "2021-08",
    "loanAmountKaran": 5000,
    "dateStartKaran": "11 aug",
    "dateEndKaran": "11 sept",
    "interestKaran": 0,
    "penaltyKaran": 0,
},{
    "year": "2021-09",
    "interestKaran": 50,

    "loanAmountKrunal": 2000,
    "dateStartKrunal": "3 sept",
    "dateEndKrunal": "3 oct",
    "interestKrunal": 0,
    "penaltyKrunal": 0,
    "loanAmountKelvin": 5000,
    "dateStartKelvin": "20 sept",
    "dateEndKelvin": "20 dec",
    "interestKelvin": 0,
    "penaltyKelvin": 0,
    "totalDeposit": "",
},{
    "year": "2021-10",
    "interestKelvin": 50,
    "interestKrunal": 20,

    "loanAmountKaran": 5000,
    "dateStartKaran": "15 oct",
    "dateEndKaran": "15 jan",
    "penaltyKaran": 0,
    "loanAmountKrunal": 3000,
    "dateStartKrunal": "3 oct",
    "dateEndKrunal": "3 nov",
    "interestKrunal": 0,
    "penaltyKrunal": 0,
    "loanAmountDhaval": 20000,
    "dateStartDhaval": "15 oct",
    "dateEndDhaval": "15 dec",
    "interestDhaval": 0,
    "penaltyDhaval": 0,
},{
    "year": "2021-11",
    "loanAmountKrunal": 2000,
    "dateStartKrunal": "7 nov",
    "dateEndKrunal": "7 dec",
    "penaltyKrunal": 30,

    "interestDhaval": 200,
    "interestKaran": 50,
    "interestKelvin": 50,
},{
    "year": "2021-12",
    "interestKrunal": 20,
    "interestKelvin": 50,

    "loanAmountVivek": 10000,
    "dateStartVivek": "11 dec",
    "dateEndVivek": "running",
    "interestVivek": 0,
    "penaltyVivek": 0,

    "loanAmountPriyal": 20000,
    "dateStartPriyal": "11 dec",
    "dateEndPriyal": "running",
    "interestPriyal": 0,
    "penaltyPriyal": 0,

    "loanAmountKaran": 2000,
    "dateStartKaran": "15 dec",
    "dateEndKaran": "15 jan",
    "interestKaran": 50,
    "penaltyKaran": 0,

    "loanAmountDhaval": 30000,
    "dateStartDhaval": "18 dec",
    "dateEndDhaval": "running",
    "interestDhaval": 200,
    "penaltyDhaval": 0,
},{
    "year": "2022-01",
    "loanAmount": 0,
    "dateStart": "",
    "dateEnd": "",
    "interestDhaval": 300,
    "interestKaran": 50+20,
    "interestPriyal": 200,
    "interestVivek": 100,
},{
    "year": "2022-02",
    "loanAmountKunj": 5000,
    "dateStartKunj": "21 feb",
    "dateEndKunj": "running",
    "interestKunj": 0,
    "penaltyKunj": 0,
    "interestDhaval": 300,
    "interestPriyal": 200,
    "interestVivek": 100,
},{
    "year": "2022-03",
    "loanAmount": 0,
    "dateStart": "",
    "dateEnd": "",
    "interestDhaval": 300,
    "interestKunj": 50,
    'interestPriyal': 200,
    'interestVivek': 100,
},{
    "year": "2022-04",
    "loanAmount": 0,
    "dateStart": "",
    "dateEnd": "",
    "interestDhaval": 300,
    "interestKunj": 50,
    'interestPriyal': 200,
    'interestVivek': 100,
}];


export const memberList = [ 
    "Kunj",
    "Vivek",
    "Pinal",
    "Jayen",
    "Priyal",
    "Brijesh",
    "Karan",
    "Krunal",
    "Dhaval",
    "Jeet",
    "Kelvin"
];

export const months = [
    "", 
    "January", 
    "February", 
    "March", 
    "April", 
    "May", 
    "June", 
    "July", 
    "August", 
    "September", 
    "October", 
    "November", 
    "December"
];


        
    

