export const Detai = [
    {
        "year": "2020-12",
        "loanAmount": 0,
        "dateStart": "",
        "dateEnd": "",
        "interest": 0,
        "penalty": 0,
    }, {
        "year": "2021-01",
        "loanAmount": 0,
        "dateStart": "",
        "dateEnd": "",
        "interest": 0,
        "penalty": 0,
    }, {
        "year": "2021-02",
        "loanAmount": 0,
        "dateStart": "",
        "dateEnd": "",
        "interest": 0,
        "penalty": 0,
    }, {
        "year": "2021-03",
        "loanAmountVivek": 12000,
        "dateStartVivek": "28 March",
        "dateEndVivek": "28 April",
        "interestVivek": 0,
        "penaltyVivek": 0,
        "loanAmountKaran": 3000,
        "dateStartKaran": "18 March",
        "dateEndKaran": "18 April",
        "interestKaran": 0,
        "penaltyKaran": 0,
    }, {
        "year": "2021-04",
        "interestVivek": 120,
        "interestKaran": 30,

        "loanAmountPinal": 5000,
        "dateStartPinal": "2 April",
        "dateEndPinal": "2 May",
        "interestPinal": 0,
        "penaltyPinal": 0,
    }, {
        "year": "2021-05",
        "interestPinal": 50,

        "loanAmountKunj": 2000,
        "dateStartKunj": "17 May",
        "dateEndKunj": "17 June",
        "interestKunj": 0,
        "penaltyKunj": 0,
        "loanAmountPriyal": 8000,
        "dateStartPriyal": "1 May",
        "dateEndPriyal": "1 June",
        "interestPriyal": 0,
        "penaltyPriyal": 0,
    }, {
        "year": "2021-06",
        "interestPriyal": 80,

        "loanAmountKunj": 2000,
        "dateStartKunj": "17 June",
        "dateEndKunj": "17 July",
        "interestKunj": 20,
        "penaltyKunj": 0,
        "loanAmountKaran": 5000,
        "dateStartKaran": "11 June",
        "dateEndKaran": "11 July",
        "interestKaran": 0,
        "penaltyKaran": 0,
    }, {
        "year": "2021-07",
        "interestKaran": 50,
        "interestKunj": 20,

        "loanAmount": 0,
        "dateStart": "",
        "dateEnd": "",
        "interest": 0,
        "penalty": 0,
    }, {
        "year": "2021-08",
        "loanAmountKaran": 5000,
        "dateStartKaran": "11 August",
        "dateEndKaran": "11 September",
        "interestKaran": 0,
        "penaltyKaran": 0,
    }, {
        "year": "2021-09",
        "interestKaran": 50,

        "loanAmountKrunal": 2000,
        "dateStartKrunal": "3 September",
        "dateEndKrunal": "3 Octomber",
        "interestKrunal": 0,
        "penaltyKrunal": 0,
        "loanAmountKelvin": 5000,
        "dateStartKelvin": "20 September",
        "dateEndKelvin": "20 December",
        "interestKelvin": 0,
        "penaltyKelvin": 0,
        "totalDeposit": "",
    }, {
        "year": "2021-10",
        "interestKelvin": 50,
        
        "loanAmountKaran": 5000,
        "dateStartKaran": "15 Octomber",
        "dateEndKaran": "15 January",
        "penaltyKaran": 0,
        "loanAmountKrunal": 3000,
        "dateStartKrunal": "3 Octomber",
        "dateEndKrunal": "3 November",
        "interestKrunal": 20,
        "penaltyKrunal": 0,
        "loanAmountDhaval": 20000,
        "dateStartDhaval": "15 Octomber",
        "dateEndDhaval": "15 December",
        "interestDhaval": 0,
        "penaltyDhaval": 0,
    }, {
        "year": "2021-11",
        "loanAmountKrunal": 2000,
        "dateStartKrunal": "7 November",
        "dateEndKrunal": "7 December",
        "penaltyKrunal": 30,

        "interestDhaval": 200,
        "interestKaran": 50,
        "interestKelvin": 50,
    }, {
        "year": "2021-12",
        "interestKrunal": 20,
        "interestKelvin": 50,

        "loanAmountVivek": 10000,
        "dateStartVivek": "11 December",
        "dateEndVivek": "Running",
        "interestVivek": 0,
        "penaltyVivek": 0,

        "loanAmountPriyal": 20000,
        "dateStartPriyal": "11 December",
        "dateEndPriyal": "Running",
        "interestPriyal": 0,
        "penaltyPriyal": 0,

        "loanAmountKaran": 2000,
        "dateStartKaran": "15 December",
        "dateEndKaran": "15 January",
        "interestKaran": 50,
        "penaltyKaran": 0,

        "loanAmountDhaval": 30000,
        "dateStartDhaval": "18 December",
        "dateEndDhaval": "Running",
        "interestDhaval": 200,
        "penaltyDhaval": 0,
    }, {
        "year": "2022-01",
        "loanAmount": 0,
        "dateStart": "",
        "dateEnd": "",
        "interestDhaval": 300,
        "interestKaran": 50 + 20,
        "interestPriyal": 200,
        "interestVivek": 100,
    }, {
        "year": "2022-02",
        "loanAmountKunj": 5000,
        "dateStartKunj": "21 February",
        "dateEndKunj": "Running",
        "interestKunj": 0,
        "penaltyKunj": 0,
        "interestDhaval": 300,
        "interestPriyal": 200,
        "interestVivek": 100,
    }, {
        "year": "2022-03",
        "loanAmount": 0,
        "dateStart": "",
        "dateEnd": "",
        "interestDhaval": 300,
        "interestKunj": 50,
        'interestPriyal': 200,
        'interestVivek': 100,
    }, {
        "year": "2022-04",
        "loanAmountKrunal": 1000,
        "dateStartKrunal": "14 April",
        "dateEndKrunal": "Running",
        "interestKrunal": 0,
        "interestDhaval": 300,
        "interestKunj": 50,
        'interestPriyal': 200,
        'interestVivek': 100,
    }, {
        "year": "2022-05",
        "loanAmountKelvin": 2000,
        "dateStartKelvin": "2 May",
        "dateEndKelvin": "3 May",
        "interestKelvin": 20,
        "loanAmountKrunal": 3000,
        "dateStartKrunal": "2 May",
        "dateEndKrunal": "Running",
        "interestKrunal": 10,
        "interestDhaval": 300,
        "interestKunj": 50,
        'interestPriyal': 200,
        'interestVivek': 100,
    }];


export const memberList = [
    "Kunj",
    "Vivek",
    "Pinal",
    "Jayen",
    "Priyal",
    "Brijesh",
    "Karan",
    "Krunal",
    "Dhaval",
    "Jeet",
    "Kelvin"
];

export const months = [
    "",
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "Octomber",
    "November",
    "December"
];





